name: Download XML Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:     # Allow manual runs too

jobs:
  fetch-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download XML file
        run: curl -L -o data.xml "https://showroom.triumphcleveland.com/unitinventory_univ.xml"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.xml
          git commit -m "Update XML file" || echo "No changes"
          git push
